### ISSUE TITLE
Off Board Vision Processing in Java - java.lang.UnsatisfiedLinkError

### ISSUE THREAD

**Issue by Kevin-OConnor** [wpilibsuite/VisionBuildSamples#3]
_From @StaleyRobotics on January 30, 2017 21:28_

`ubuntu@tegra-ubuntu:~/Downloads/Java/output$ sh runCameraVision
Exception in thread "main" java.lang.UnsatisfiedLinkError: /home/ubuntu/Downloads/Java/output/libopencv_java310.so: /home/ubuntu/Downloads/Java/output/libopencv_java310.so: wrong ELF class: ELFCLASS32 (Possible cause: architecture word width mismatch)
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1857)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at Main.main(Main.java:12)
`
I am getting this error after successfully running `./gradlew build`

My team is new to the Jetson and our end goal is to do our vision processing useing Open CV in Python 2.7 on the Jetson TX1. I am also having problems connecting the Jetson over Ethernet to view Network Tables. 

_Copied from original issue: wpilibsuite/allwpilib#475_

**Comment by ThadHouse** [comment]
The builds provided for the Java armhf build system do not work on the TX1. I didn't realize they had switched the TX1 to be AArch64 instead of armhf. I will look into getting builds, but I do not know when I will be able to get them. I will update the docs for now, but for now you will need to build all the native libraries manually.
